[package]
name = "ferric-event-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
anyhow = "1.0.100"
rand = "0.9.2"
tower-http = { version = "0.6.6", features = ["catch-panic"] }
