services:
  event-db:
    image: postgres:18
    restart: always
    # shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventdb
    volumes:
      - database:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    
volumes:
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'database/init'